version = 0.1
[default.deploy.parameters]
stack_name = "aws-application-composer-example"
resolve_s3 = true
s3_prefix = "aws-application-composer-example"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
